build:
  environment:
    sdkman:
      - java@13.0.2-open
      - kotlin@1.3.70
      - gradle@6.3
  nodes:
    deploy:
      requires:
        - branch: main
    tests-with-coverage:
      tests:
        override:
          - command: gradle clean test
            coverage:
              file: 'build/reports/jacoco/test/jacocoTestReport.xml'
              format: 'jacoco'
    analysis:
      tests:
        override:
          - java-scrutinizer-run
